# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - davidcloudobi-github-action-demo-test(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name:  Start SQL Server 😘
      run: |
        docker run -d -p 1433:1433 -e sa_password=Ollasystems123# -d -e ACCEPT_EULA=Y microsoft/mssql-server-windows-developer:latest
    - name: Sleep for 5 seconds 😴
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'

    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Run automated tests 🎙️
      env:
        ConnectionStrings__DefaultConnection: Server=localhost;Database=CustomerGitHubActionsCICD_Test;User=sa;Password=Ollasystems123#;
      run: dotnet test -c Release --no-build

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: davidcloudobi-github-action-demo-test
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_69268DA4C26C4E3881C7185B21395750 }}
        package: ${{env.DOTNET_ROOT}}/myapp

